spring:
  application:
    name: gopface
    
urls: http://*:5100
Logging:
  ConfigFile: ./Config/nlog.config
Databases:
  Mssql:
    Main:
      ConnectionString: Data Source=42.112.35.52,62113;Initial Catalog=GOPFACE_MAIN_DEV;Persist Security Info=True;User ID=sa;Password=iken@123;MultipleActiveResultSets=True
  Mongo:
    Main:
      ConnectionString: mongodb://42.112.35.55:27017
      DatabaseName: GOPFACE_MAIN_DEV
      Ssl: false
  Elasticsearch:
    Address: http://42.112.35.55:9200
    Mapping:
      EsPost:
        IndexName: gopface_post_dev
        TypeName: post_dev
Kafka:
  Servers: 42.112.35.55:9092
  TopicMap:
    FbExtractedPost: fb_extracted_post-20180627_150000
    GopfacePost: gopface_post-20180627_150000
    SourcePostStatistic: source_post_statistic-20180627_150000
  ProducerConfigs:
    common:
  ConsumerConfigs:
    common:
      auto.commit.interval.ms: 5000
      auto.offset.reset: earliest,
      enable.auto.offset.store: false

---  
spring:
  profiles: hoinx01
server:
  port: 2

