spring:
  application:
    name: gopface
hoinx:
  name: nguyen xuan hoi local
  age: 10
server:
  port: 1

---  
spring:
  profiles: hoinx01
server:
  port: 2
  
---  
spring:
  profiles: hoinx02
server:
  port: 3
