spring:
  application:
    name: gopface
hoinx:
  name: nguyen xuan hoi 01
  age: 10
server:
  port: 1

---  
spring:
  profiles: dev
server:
  port: 2
  
---  
spring:
  profiles: production
server:
  port: 3
